-- SINH TỰ ĐỘNG bởi scripts/gen-migrations.mjs từ src/data/*.js
-- Đừng sửa tay file này. Sửa nguồn rồi chạy lại script.


-- Hãng xe
insert into brands (name, slug, sort_order) values
  ('Toyota', 'toyota', 0),
  ('Hyundai', 'hyundai', 1),
  ('Kia', 'kia', 2),
  ('Mazda', 'mazda', 3),
  ('Honda', 'honda', 4),
  ('Ford', 'ford', 5),
  ('Mitsubishi', 'mitsubishi', 6),
  ('VinFast', 'vinfast', 7),
  ('Mercedes-Benz', 'mercedes-benz', 8),
  ('BMW', 'bmw', 9),
  ('Audi', 'audi', 10),
  ('Lexus', 'lexus', 11),
  ('Volvo', 'volvo', 12),
  ('Porsche', 'porsche', 13),
  ('Peugeot', 'peugeot', 14),
  ('Subaru', 'subaru', 15),
  ('Nissan', 'nissan', 16),
  ('Suzuki', 'suzuki', 17),
  ('Isuzu', 'isuzu', 18),
  ('MG', 'mg', 19),
  ('Skoda', 'skoda', 20),
  ('Haval', 'haval', 21),
  ('Wuling', 'wuling', 22),
  ('BYD', 'byd', 23),
  ('Chevrolet', 'chevrolet', 24),
  ('Volkswagen', 'volkswagen', 25)
on conflict (name) do nothing;

-- Dòng xe
insert into models (brand_id, name, slug) values
  ((select id from brands where name = 'Toyota'), 'Vios', 'vios'),
  ((select id from brands where name = 'Toyota'), 'Innova', 'innova'),
  ((select id from brands where name = 'Toyota'), 'Innova Cross', 'innova-cross'),
  ((select id from brands where name = 'Toyota'), 'Camry', 'camry'),
  ((select id from brands where name = 'Toyota'), 'Fortuner', 'fortuner'),
  ((select id from brands where name = 'Toyota'), 'Corolla Altis', 'corolla-altis'),
  ((select id from brands where name = 'Toyota'), 'Corolla Cross', 'corolla-cross'),
  ((select id from brands where name = 'Toyota'), 'Yaris', 'yaris'),
  ((select id from brands where name = 'Toyota'), 'Yaris Cross', 'yaris-cross'),
  ((select id from brands where name = 'Toyota'), 'Raize', 'raize'),
  ((select id from brands where name = 'Toyota'), 'Hilux', 'hilux'),
  ((select id from brands where name = 'Toyota'), 'Land Cruiser', 'land-cruiser'),
  ((select id from brands where name = 'Toyota'), 'Land Cruiser Prado', 'land-cruiser-prado'),
  ((select id from brands where name = 'Toyota'), 'Alphard', 'alphard'),
  ((select id from brands where name = 'Toyota'), 'Avanza Premio', 'avanza-premio'),
  ((select id from brands where name = 'Toyota'), 'Veloz Cross', 'veloz-cross'),
  ((select id from brands where name = 'Hyundai'), 'Grand i10', 'grand-i10'),
  ((select id from brands where name = 'Hyundai'), 'Accent', 'accent'),
  ((select id from brands where name = 'Hyundai'), 'Elantra', 'elantra'),
  ((select id from brands where name = 'Hyundai'), 'Creta', 'creta'),
  ((select id from brands where name = 'Hyundai'), 'Tucson', 'tucson'),
  ((select id from brands where name = 'Hyundai'), 'Santa Fe', 'santa-fe'),
  ((select id from brands where name = 'Hyundai'), 'Palisade', 'palisade'),
  ((select id from brands where name = 'Hyundai'), 'Stargazer', 'stargazer'),
  ((select id from brands where name = 'Hyundai'), 'Custin', 'custin'),
  ((select id from brands where name = 'Hyundai'), 'Ioniq 5', 'ioniq-5'),
  ((select id from brands where name = 'Hyundai'), 'Venue', 'venue'),
  ((select id from brands where name = 'Hyundai'), 'Kona', 'kona'),
  ((select id from brands where name = 'Hyundai'), 'Solati', 'solati'),
  ((select id from brands where name = 'Kia'), 'Morning', 'morning'),
  ((select id from brands where name = 'Kia'), 'Soluto', 'soluto'),
  ((select id from brands where name = 'Kia'), 'K3', 'k3'),
  ((select id from brands where name = 'Kia'), 'K5', 'k5'),
  ((select id from brands where name = 'Kia'), 'Sonet', 'sonet'),
  ((select id from brands where name = 'Kia'), 'Seltos', 'seltos'),
  ((select id from brands where name = 'Kia'), 'Sportage', 'sportage'),
  ((select id from brands where name = 'Kia'), 'Sorento', 'sorento'),
  ((select id from brands where name = 'Kia'), 'Carnival', 'carnival'),
  ((select id from brands where name = 'Kia'), 'Carens', 'carens'),
  ((select id from brands where name = 'Kia'), 'Cerato', 'cerato'),
  ((select id from brands where name = 'Kia'), 'Sedona', 'sedona'),
  ((select id from brands where name = 'Mazda'), 'Mazda 2', 'mazda-2'),
  ((select id from brands where name = 'Mazda'), 'Mazda 3', 'mazda-3'),
  ((select id from brands where name = 'Mazda'), 'Mazda 6', 'mazda-6'),
  ((select id from brands where name = 'Mazda'), 'CX-3', 'cx-3'),
  ((select id from brands where name = 'Mazda'), 'CX-30', 'cx-30'),
  ((select id from brands where name = 'Mazda'), 'CX-5', 'cx-5'),
  ((select id from brands where name = 'Mazda'), 'CX-8', 'cx-8'),
  ((select id from brands where name = 'Mazda'), 'BT-50', 'bt-50'),
  ((select id from brands where name = 'Honda'), 'Brio', 'brio'),
  ((select id from brands where name = 'Honda'), 'City', 'city'),
  ((select id from brands where name = 'Honda'), 'Civic', 'civic'),
  ((select id from brands where name = 'Honda'), 'Accord', 'accord'),
  ((select id from brands where name = 'Honda'), 'HR-V', 'hr-v'),
  ((select id from brands where name = 'Honda'), 'CR-V', 'cr-v'),
  ((select id from brands where name = 'Honda'), 'BR-V', 'br-v'),
  ((select id from brands where name = 'Ford'), 'Ranger', 'ranger'),
  ((select id from brands where name = 'Ford'), 'Everest', 'everest'),
  ((select id from brands where name = 'Ford'), 'Explorer', 'explorer'),
  ((select id from brands where name = 'Ford'), 'Territory', 'territory'),
  ((select id from brands where name = 'Ford'), 'Transit', 'transit'),
  ((select id from brands where name = 'Ford'), 'EcoSport', 'ecosport'),
  ((select id from brands where name = 'Ford'), 'Focus', 'focus'),
  ((select id from brands where name = 'Mitsubishi'), 'Attrage', 'attrage'),
  ((select id from brands where name = 'Mitsubishi'), 'Xpander', 'xpander'),
  ((select id from brands where name = 'Mitsubishi'), 'Xpander Cross', 'xpander-cross'),
  ((select id from brands where name = 'Mitsubishi'), 'Outlander', 'outlander'),
  ((select id from brands where name = 'Mitsubishi'), 'Pajero Sport', 'pajero-sport'),
  ((select id from brands where name = 'Mitsubishi'), 'Triton', 'triton'),
  ((select id from brands where name = 'VinFast'), 'Fadil', 'fadil'),
  ((select id from brands where name = 'VinFast'), 'VF 3', 'vf-3'),
  ((select id from brands where name = 'VinFast'), 'VF 5', 'vf-5'),
  ((select id from brands where name = 'VinFast'), 'VF e34', 'vf-e34'),
  ((select id from brands where name = 'VinFast'), 'VF 6', 'vf-6'),
  ((select id from brands where name = 'VinFast'), 'VF 7', 'vf-7'),
  ((select id from brands where name = 'VinFast'), 'VF 8', 'vf-8'),
  ((select id from brands where name = 'VinFast'), 'VF 9', 'vf-9'),
  ((select id from brands where name = 'VinFast'), 'Lux A2.0', 'lux-a2-0'),
  ((select id from brands where name = 'VinFast'), 'Lux SA2.0', 'lux-sa2-0'),
  ((select id from brands where name = 'VinFast'), 'President', 'president'),
  ((select id from brands where name = 'Mercedes-Benz'), 'C-Class', 'c-class'),
  ((select id from brands where name = 'Mercedes-Benz'), 'E-Class', 'e-class'),
  ((select id from brands where name = 'Mercedes-Benz'), 'S-Class', 's-class'),
  ((select id from brands where name = 'Mercedes-Benz'), 'GLC', 'glc'),
  ((select id from brands where name = 'Mercedes-Benz'), 'GLE', 'gle'),
  ((select id from brands where name = 'Mercedes-Benz'), 'GLS', 'gls'),
  ((select id from brands where name = 'Mercedes-Benz'), 'Maybach', 'maybach'),
  ((select id from brands where name = 'Mercedes-Benz'), 'G-Class', 'g-class'),
  ((select id from brands where name = 'Mercedes-Benz'), 'V-Class', 'v-class'),
  ((select id from brands where name = 'Mercedes-Benz'), 'EQB', 'eqb'),
  ((select id from brands where name = 'Mercedes-Benz'), 'EQE', 'eqe'),
  ((select id from brands where name = 'Mercedes-Benz'), 'EQS', 'eqs'),
  ((select id from brands where name = 'BMW'), '3 Series', '3-series'),
  ((select id from brands where name = 'BMW'), '5 Series', '5-series'),
  ((select id from brands where name = 'BMW'), '7 Series', '7-series'),
  ((select id from brands where name = 'BMW'), 'X3', 'x3'),
  ((select id from brands where name = 'BMW'), 'X4', 'x4'),
  ((select id from brands where name = 'BMW'), 'X5', 'x5'),
  ((select id from brands where name = 'BMW'), 'X6', 'x6'),
  ((select id from brands where name = 'BMW'), 'X7', 'x7'),
  ((select id from brands where name = 'BMW'), 'Z4', 'z4'),
  ((select id from brands where name = 'BMW'), 'i4', 'i4'),
  ((select id from brands where name = 'BMW'), 'i7', 'i7'),
  ((select id from brands where name = 'BMW'), 'iX3', 'ix3'),
  ((select id from brands where name = 'Audi'), 'A3', 'a3'),
  ((select id from brands where name = 'Audi'), 'A4', 'a4'),
  ((select id from brands where name = 'Audi'), 'A6', 'a6'),
  ((select id from brands where name = 'Audi'), 'A8', 'a8'),
  ((select id from brands where name = 'Audi'), 'Q2', 'q2'),
  ((select id from brands where name = 'Audi'), 'Q3', 'q3'),
  ((select id from brands where name = 'Audi'), 'Q5', 'q5'),
  ((select id from brands where name = 'Audi'), 'Q7', 'q7'),
  ((select id from brands where name = 'Audi'), 'Q8', 'q8'),
  ((select id from brands where name = 'Audi'), 'e-tron', 'e-tron'),
  ((select id from brands where name = 'Lexus'), 'ES', 'es'),
  ((select id from brands where name = 'Lexus'), 'LS', 'ls'),
  ((select id from brands where name = 'Lexus'), 'NX', 'nx'),
  ((select id from brands where name = 'Lexus'), 'RX', 'rx'),
  ((select id from brands where name = 'Lexus'), 'GX', 'gx'),
  ((select id from brands where name = 'Lexus'), 'LX', 'lx'),
  ((select id from brands where name = 'Lexus'), 'LM', 'lm'),
  ((select id from brands where name = 'Lexus'), 'IS', 'is'),
  ((select id from brands where name = 'Volvo'), 'XC40', 'xc40'),
  ((select id from brands where name = 'Volvo'), 'XC60', 'xc60'),
  ((select id from brands where name = 'Volvo'), 'XC90', 'xc90'),
  ((select id from brands where name = 'Volvo'), 'S90', 's90'),
  ((select id from brands where name = 'Volvo'), 'V60', 'v60'),
  ((select id from brands where name = 'Porsche'), 'Macan', 'macan'),
  ((select id from brands where name = 'Porsche'), 'Cayenne', 'cayenne'),
  ((select id from brands where name = 'Porsche'), 'Panamera', 'panamera'),
  ((select id from brands where name = 'Porsche'), 'Taycan', 'taycan'),
  ((select id from brands where name = 'Porsche'), '911', '911'),
  ((select id from brands where name = 'Peugeot'), '2008', '2008'),
  ((select id from brands where name = 'Peugeot'), '3008', '3008'),
  ((select id from brands where name = 'Peugeot'), '5008', '5008'),
  ((select id from brands where name = 'Peugeot'), '408', '408'),
  ((select id from brands where name = 'Peugeot'), 'Traveller', 'traveller'),
  ((select id from brands where name = 'Subaru'), 'Forester', 'forester'),
  ((select id from brands where name = 'Subaru'), 'Outback', 'outback'),
  ((select id from brands where name = 'Subaru'), 'BRZ', 'brz'),
  ((select id from brands where name = 'Subaru'), 'WRX', 'wrx'),
  ((select id from brands where name = 'Nissan'), 'Almera', 'almera'),
  ((select id from brands where name = 'Nissan'), 'Kicks', 'kicks'),
  ((select id from brands where name = 'Nissan'), 'Navara', 'navara'),
  ((select id from brands where name = 'Nissan'), 'Terra', 'terra'),
  ((select id from brands where name = 'Suzuki'), 'Swift', 'swift'),
  ((select id from brands where name = 'Suzuki'), 'Ertiga', 'ertiga'),
  ((select id from brands where name = 'Suzuki'), 'XL7', 'xl7'),
  ((select id from brands where name = 'Suzuki'), 'Jimny', 'jimny'),
  ((select id from brands where name = 'Suzuki'), 'Ciaz', 'ciaz'),
  ((select id from brands where name = 'Suzuki'), 'Blind Van', 'blind-van'),
  ((select id from brands where name = 'Isuzu'), 'D-Max', 'd-max'),
  ((select id from brands where name = 'Isuzu'), 'mu-X', 'mu-x'),
  ((select id from brands where name = 'MG'), 'MG5', 'mg5'),
  ((select id from brands where name = 'MG'), 'ZS', 'zs'),
  ((select id from brands where name = 'MG'), 'HS', 'hs'),
  ((select id from brands where name = 'MG'), 'RX5', 'rx5'),
  ((select id from brands where name = 'Skoda'), 'Karoq', 'karoq'),
  ((select id from brands where name = 'Skoda'), 'Kodiaq', 'kodiaq'),
  ((select id from brands where name = 'Haval'), 'H6', 'h6'),
  ((select id from brands where name = 'Wuling'), 'HongGuang MiniEV', 'hongguang-miniev'),
  ((select id from brands where name = 'BYD'), 'Atto 3', 'atto-3'),
  ((select id from brands where name = 'BYD'), 'Dolphin', 'dolphin'),
  ((select id from brands where name = 'BYD'), 'Seal', 'seal'),
  ((select id from brands where name = 'Chevrolet'), 'Colorado', 'colorado'),
  ((select id from brands where name = 'Chevrolet'), 'Trailblazer', 'trailblazer'),
  ((select id from brands where name = 'Chevrolet'), 'Cruze', 'cruze'),
  ((select id from brands where name = 'Chevrolet'), 'Spark', 'spark'),
  ((select id from brands where name = 'Volkswagen'), 'Teramont', 'teramont'),
  ((select id from brands where name = 'Volkswagen'), 'Tiguan', 'tiguan'),
  ((select id from brands where name = 'Volkswagen'), 'Touareg', 'touareg'),
  ((select id from brands where name = 'Volkswagen'), 'Virtus', 'virtus'),
  ((select id from brands where name = 'Volkswagen'), 'T-Cross', 't-cross')
on conflict (brand_id, name) do nothing;

-- Tỉnh/thành
insert into provinces (name, slug, is_major, sort_order) values
  ('TP.HCM', 'tp-hcm', true, 0),
  ('Hà Nội', 'ha-noi', true, 1),
  ('Đà Nẵng', 'da-nang', true, 2),
  ('Hải Phòng', 'hai-phong', true, 3),
  ('Cần Thơ', 'can-tho', true, 4),
  ('Bà Rịa - Vũng Tàu', 'ba-ria-vung-tau', false, 5),
  ('Bình Dương', 'binh-duong', false, 6),
  ('Đồng Nai', 'dong-nai', false, 7),
  ('Khánh Hòa', 'khanh-hoa', false, 8),
  ('Lâm Đồng', 'lam-dong', false, 9),
  ('Quảng Ninh', 'quang-ninh', false, 10),
  ('Thanh Hóa', 'thanh-hoa', false, 11),
  ('Nghệ An', 'nghe-an', false, 12),
  ('Thừa Thiên Huế', 'thua-thien-hue', false, 13),
  ('Quảng Nam', 'quang-nam', false, 14),
  ('Bình Định', 'binh-dinh', false, 15),
  ('Phú Yên', 'phu-yen', false, 16),
  ('Bình Thuận', 'binh-thuan', false, 17),
  ('Ninh Thuận', 'ninh-thuan', false, 18),
  ('Gia Lai', 'gia-lai', false, 19),
  ('Đắk Lắk', 'dak-lak', false, 20),
  ('Lào Cai', 'lao-cai', false, 21),
  ('Vĩnh Phúc', 'vinh-phuc', false, 22),
  ('Bắc Ninh', 'bac-ninh', false, 23),
  ('Hải Dương', 'hai-duong', false, 24),
  ('Hưng Yên', 'hung-yen', false, 25),
  ('Nam Định', 'nam-dinh', false, 26),
  ('Thái Bình', 'thai-binh', false, 27),
  ('Ninh Bình', 'ninh-binh', false, 28),
  ('Long An', 'long-an', false, 29),
  ('Tiền Giang', 'tien-giang', false, 30),
  ('Kiên Giang', 'kien-giang', false, 31),
  ('An Giang', 'an-giang', false, 32),
  ('Sóc Trăng', 'soc-trang', false, 33),
  ('Cà Mau', 'ca-mau', false, 34),
  ('Đắk Nông', 'dak-nong', false, 35),
  ('Kon Tum', 'kon-tum', false, 36),
  ('Bình Phước', 'binh-phuoc', false, 37),
  ('Tây Ninh', 'tay-ninh', false, 38)
on conflict (name) do nothing;

-- Quận/huyện (chỉ 5 thành phố lớn)
insert into districts (province_id, name, slug) values
  ((select id from provinces where name = 'TP.HCM'), 'Quận 1', 'quan-1'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 3', 'quan-3'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 4', 'quan-4'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 5', 'quan-5'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 6', 'quan-6'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 7', 'quan-7'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 8', 'quan-8'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 10', 'quan-10'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 11', 'quan-11'),
  ((select id from provinces where name = 'TP.HCM'), 'Quận 12', 'quan-12'),
  ((select id from provinces where name = 'TP.HCM'), 'Bình Thạnh', 'binh-thanh'),
  ((select id from provinces where name = 'TP.HCM'), 'Gò Vấp', 'go-vap'),
  ((select id from provinces where name = 'TP.HCM'), 'Phú Nhuận', 'phu-nhuan'),
  ((select id from provinces where name = 'TP.HCM'), 'Tân Bình', 'tan-binh'),
  ((select id from provinces where name = 'TP.HCM'), 'Tân Phú', 'tan-phu'),
  ((select id from provinces where name = 'TP.HCM'), 'Bình Tân', 'binh-tan'),
  ((select id from provinces where name = 'TP.HCM'), 'Bình Chánh', 'binh-chanh'),
  ((select id from provinces where name = 'TP.HCM'), 'Cần Giờ', 'can-gio'),
  ((select id from provinces where name = 'TP.HCM'), 'Củ Chi', 'cu-chi'),
  ((select id from provinces where name = 'TP.HCM'), 'Hóc Môn', 'hoc-mon'),
  ((select id from provinces where name = 'TP.HCM'), 'Nhà Bè', 'nha-be'),
  ((select id from provinces where name = 'TP.HCM'), 'Thủ Đức', 'thu-duc'),
  ((select id from provinces where name = 'Hà Nội'), 'Hoàn Kiếm', 'hoan-kiem'),
  ((select id from provinces where name = 'Hà Nội'), 'Ba Đình', 'ba-dinh'),
  ((select id from provinces where name = 'Hà Nội'), 'Đống Đa', 'dong-da'),
  ((select id from provinces where name = 'Hà Nội'), 'Hai Bà Trưng', 'hai-ba-trung'),
  ((select id from provinces where name = 'Hà Nội'), 'Hoàng Mai', 'hoang-mai'),
  ((select id from provinces where name = 'Hà Nội'), 'Long Biên', 'long-bien'),
  ((select id from provinces where name = 'Hà Nội'), 'Tây Hồ', 'tay-ho'),
  ((select id from provinces where name = 'Hà Nội'), 'Cầu Giấy', 'cau-giay'),
  ((select id from provinces where name = 'Hà Nội'), 'Thanh Xuân', 'thanh-xuan'),
  ((select id from provinces where name = 'Hà Nội'), 'Hà Đông', 'ha-dong'),
  ((select id from provinces where name = 'Hà Nội'), 'Đông Anh', 'dong-anh'),
  ((select id from provinces where name = 'Hà Nội'), 'Gia Lâm', 'gia-lam'),
  ((select id from provinces where name = 'Hà Nội'), 'Sóc Sơn', 'soc-son'),
  ((select id from provinces where name = 'Hà Nội'), 'Từ Liêm', 'tu-liem'),
  ((select id from provinces where name = 'Hà Nội'), 'Thường Tín', 'thuong-tin'),
  ((select id from provinces where name = 'Hà Nội'), 'Mê Linh', 'me-linh'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Hải Châu', 'hai-chau'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Thanh Khê', 'thanh-khe'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Liên Chiểu', 'lien-chieu'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Ngũ Hành Sơn', 'ngu-hanh-son'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Sơn Trà', 'son-tra'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Cẩm Lệ', 'cam-le'),
  ((select id from provinces where name = 'Đà Nẵng'), 'Hòa Vang', 'hoa-vang'),
  ((select id from provinces where name = 'Hải Phòng'), 'Hồng Bàng', 'hong-bang'),
  ((select id from provinces where name = 'Hải Phòng'), 'Ngô Quyền', 'ngo-quyen'),
  ((select id from provinces where name = 'Hải Phòng'), 'Lê Chân', 'le-chan'),
  ((select id from provinces where name = 'Hải Phòng'), 'Kiến An', 'kien-an'),
  ((select id from provinces where name = 'Hải Phòng'), 'Hải An', 'hai-an'),
  ((select id from provinces where name = 'Hải Phòng'), 'Đồ Sơn', 'do-son'),
  ((select id from provinces where name = 'Hải Phòng'), 'Dương Kinh', 'duong-kinh'),
  ((select id from provinces where name = 'Hải Phòng'), 'Thuỷ Nguyên', 'thuy-nguyen'),
  ((select id from provinces where name = 'Hải Phòng'), 'An Dương', 'an-duong'),
  ((select id from provinces where name = 'Hải Phòng'), 'An Lão', 'an-lao'),
  ((select id from provinces where name = 'Hải Phòng'), 'Kiến Thụy', 'kien-thuy'),
  ((select id from provinces where name = 'Hải Phòng'), 'Tiên Lãng', 'tien-lang'),
  ((select id from provinces where name = 'Hải Phòng'), 'Vĩnh Bảo', 'vinh-bao'),
  ((select id from provinces where name = 'Hải Phòng'), 'Cát Hải', 'cat-hai'),
  ((select id from provinces where name = 'Cần Thơ'), 'Ninh Kiều', 'ninh-kieu'),
  ((select id from provinces where name = 'Cần Thơ'), 'Bình Thủy', 'binh-thuy'),
  ((select id from provinces where name = 'Cần Thơ'), 'Cái Răng', 'cai-rang'),
  ((select id from provinces where name = 'Cần Thơ'), 'Ô Môn', 'o-mon'),
  ((select id from provinces where name = 'Cần Thơ'), 'Thốt Nốt', 'thot-not'),
  ((select id from provinces where name = 'Cần Thơ'), 'Phong Điền', 'phong-dien'),
  ((select id from provinces where name = 'Cần Thơ'), 'Cờ Đỏ', 'co-do'),
  ((select id from provinces where name = 'Cần Thơ'), 'Thới Lai', 'thoi-lai'),
  ((select id from provinces where name = 'Cần Thơ'), 'Vĩnh Thạnh', 'vinh-thanh')
on conflict (province_id, name) do nothing;

-- Tiện nghi
insert into amenities (code, name, icon, sort_order) values
  ('ban_do', 'Bản đồ', 'Map', 0),
  ('camera_360', 'Camera 360', 'Aperture', 1),
  ('cam_hanh_trinh', 'Camera hành trình', 'Video', 2),
  ('cam_lui', 'Camera lùi', 'CameraOff', 3),
  ('cam_bien_lop', 'Cảm biến lốp', 'Gauge', 4),
  ('gps', 'Định vị GPS', 'Navigation', 5),
  ('etc', 'Thu phí không dừng (ETC)', 'CreditCard', 6),
  ('tui_khi', 'Túi khí an toàn', 'ShieldCheck', 7),
  ('lop_du_phong', 'Lốp dự phòng', 'CircleDot', 8),
  ('cam_bien_va_cham', 'Cảm biến va chạm', 'Radar', 9),
  ('cua_so_troi', 'Cửa sổ trời', 'Sun', 10),
  ('adas', 'Hỗ trợ lái ADAS', 'Cpu', 11),
  ('ghe_da', 'Ghế da', 'Armchair', 12)
on conflict (code) do nothing;
